name: voicely
description: A voice translation app built with Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  http: ^1.1.0
  provider: ^6.1.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  google_ml_kit: ^0.16.3
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  flag: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/playstore.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/playstore.png"
  remove_alpha_ios: true 